version: '3'
services:
  whats_cooking:
    image: whats_cooking
    build:
      dockerfile: Dockerfile
      context: ./whats-cooking
    volumes:
      - /root/.m2/repository
    ports:
      - 5000:5000